/*
 * Gitea API
 *
 * This documentation describes the Gitea API.
 *
 * The version of the OpenAPI document: 1.22.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// EditPullRequestOption options when modify pull request
    /// </summary>
    [DataContract(Name = "EditPullRequestOption")]
    public partial class EditPullRequestOption : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="EditPullRequestOption" /> class.
        /// </summary>
        /// <param name="allowMaintainerEdit">allowMaintainerEdit.</param>
        /// <param name="assignee">assignee.</param>
        /// <param name="assignees">assignees.</param>
        /// <param name="varBase">varBase.</param>
        /// <param name="body">body.</param>
        /// <param name="dueDate">dueDate.</param>
        /// <param name="labels">labels.</param>
        /// <param name="milestone">milestone.</param>
        /// <param name="state">state.</param>
        /// <param name="title">title.</param>
        /// <param name="unsetDueDate">unsetDueDate.</param>
        public EditPullRequestOption(bool allowMaintainerEdit = default(bool), string assignee = default(string), List<string> assignees = default(List<string>), string varBase = default(string), string body = default(string), DateTime dueDate = default(DateTime), List<long> labels = default(List<long>), long milestone = default(long), string state = default(string), string title = default(string), bool unsetDueDate = default(bool))
        {
            this.AllowMaintainerEdit = allowMaintainerEdit;
            this.Assignee = assignee;
            this.Assignees = assignees;
            this.Base = varBase;
            this.Body = body;
            this.DueDate = dueDate;
            this.Labels = labels;
            this.Milestone = milestone;
            this.State = state;
            this.Title = title;
            this.UnsetDueDate = unsetDueDate;
        }

        /// <summary>
        /// Gets or Sets AllowMaintainerEdit
        /// </summary>
        [DataMember(Name = "allow_maintainer_edit", EmitDefaultValue = true)]
        public bool AllowMaintainerEdit { get; set; }

        /// <summary>
        /// Gets or Sets Assignee
        /// </summary>
        [DataMember(Name = "assignee", EmitDefaultValue = false)]
        public string Assignee { get; set; }

        /// <summary>
        /// Gets or Sets Assignees
        /// </summary>
        [DataMember(Name = "assignees", EmitDefaultValue = false)]
        public List<string> Assignees { get; set; }

        /// <summary>
        /// Gets or Sets Base
        /// </summary>
        [DataMember(Name = "base", EmitDefaultValue = false)]
        public string Base { get; set; }

        /// <summary>
        /// Gets or Sets Body
        /// </summary>
        [DataMember(Name = "body", EmitDefaultValue = false)]
        public string Body { get; set; }

        /// <summary>
        /// Gets or Sets DueDate
        /// </summary>
        [DataMember(Name = "due_date", EmitDefaultValue = false)]
        public DateTime DueDate { get; set; }

        /// <summary>
        /// Gets or Sets Labels
        /// </summary>
        [DataMember(Name = "labels", EmitDefaultValue = false)]
        public List<long> Labels { get; set; }

        /// <summary>
        /// Gets or Sets Milestone
        /// </summary>
        [DataMember(Name = "milestone", EmitDefaultValue = false)]
        public long Milestone { get; set; }

        /// <summary>
        /// Gets or Sets State
        /// </summary>
        [DataMember(Name = "state", EmitDefaultValue = false)]
        public string State { get; set; }

        /// <summary>
        /// Gets or Sets Title
        /// </summary>
        [DataMember(Name = "title", EmitDefaultValue = false)]
        public string Title { get; set; }

        /// <summary>
        /// Gets or Sets UnsetDueDate
        /// </summary>
        [DataMember(Name = "unset_due_date", EmitDefaultValue = true)]
        public bool UnsetDueDate { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class EditPullRequestOption {\n");
            sb.Append("  AllowMaintainerEdit: ").Append(AllowMaintainerEdit).Append("\n");
            sb.Append("  Assignee: ").Append(Assignee).Append("\n");
            sb.Append("  Assignees: ").Append(Assignees).Append("\n");
            sb.Append("  Base: ").Append(Base).Append("\n");
            sb.Append("  Body: ").Append(Body).Append("\n");
            sb.Append("  DueDate: ").Append(DueDate).Append("\n");
            sb.Append("  Labels: ").Append(Labels).Append("\n");
            sb.Append("  Milestone: ").Append(Milestone).Append("\n");
            sb.Append("  State: ").Append(State).Append("\n");
            sb.Append("  Title: ").Append(Title).Append("\n");
            sb.Append("  UnsetDueDate: ").Append(UnsetDueDate).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
