/*
 * Gitea API
 *
 * This documentation describes the Gitea API.
 *
 * The version of the OpenAPI document: 1.22.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Org.OpenAPITools.Client.OpenAPIDateConverter;

namespace Org.OpenAPITools.Model
{
    /// <summary>
    /// IssueLabelsOption a collection of labels
    /// </summary>
    [DataContract(Name = "IssueLabelsOption")]
    public partial class IssueLabelsOption : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="IssueLabelsOption" /> class.
        /// </summary>
        /// <param name="labels">Labels can be a list of integers representing label IDs or a list of strings representing label names.</param>
        public IssueLabelsOption(List<Object> labels = default(List<Object>))
        {
            this.Labels = labels;
        }

        /// <summary>
        /// Labels can be a list of integers representing label IDs or a list of strings representing label names
        /// </summary>
        /// <value>Labels can be a list of integers representing label IDs or a list of strings representing label names</value>
        [DataMember(Name = "labels", EmitDefaultValue = false)]
        public List<Object> Labels { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class IssueLabelsOption {\n");
            sb.Append("  Labels: ").Append(Labels).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
