/*
 * Gitea API
 *
 * This documentation describes the Gitea API.
 *
 * The version of the OpenAPI document: 1.22.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */

using System;
using System.IO;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.Reflection;
using RestSharp;
using Xunit;

using Org.OpenAPITools.Client;
using Org.OpenAPITools.Api;
// uncomment below to import models
//using Org.OpenAPITools.Model;

namespace Org.OpenAPITools.Test.Api
{
    /// <summary>
    ///  Class for testing ActivitypubApi
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the API endpoint.
    /// </remarks>
    public class ActivitypubApiTests : IDisposable
    {
        private ActivitypubApi instance;

        public ActivitypubApiTests()
        {
            instance = new ActivitypubApi();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ActivitypubApi
        /// </summary>
        [Fact]
        public void InstanceTest()
        {
            // TODO uncomment below to test 'IsType' ActivitypubApi
            //Assert.IsType<ActivitypubApi>(instance);
        }

        /// <summary>
        /// Test ActivitypubPerson
        /// </summary>
        [Fact]
        public void ActivitypubPersonTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int userId = null;
            //var response = instance.ActivitypubPerson(userId);
            //Assert.IsType<ActivityPub>(response);
        }

        /// <summary>
        /// Test ActivitypubPersonInbox
        /// </summary>
        [Fact]
        public void ActivitypubPersonInboxTest()
        {
            // TODO uncomment below to test the method and replace null with proper value
            //int userId = null;
            //instance.ActivitypubPersonInbox(userId);
        }
    }
}
