/*
 * Gitea API
 *
 * This documentation describes the Gitea API.
 *
 * The version of the OpenAPI document: 1.22.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using System;
using System.Collections;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Linq;
using System.IO;
using System.Runtime.Serialization;
using System.Text;
using System.Text.RegularExpressions;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using Newtonsoft.Json.Linq;
using System.ComponentModel.DataAnnotations;
using OpenAPIDateConverter = Gitea.Net.Client.OpenAPIDateConverter;

namespace Gitea.Net.Model
{
    /// <summary>
    /// Commit
    /// </summary>
    [DataContract(Name = "Commit")]
    public partial class Commit : IValidatableObject
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="Commit" /> class.
        /// </summary>
        /// <param name="author">author.</param>
        /// <param name="varCommit">varCommit.</param>
        /// <param name="committer">committer.</param>
        /// <param name="created">created.</param>
        /// <param name="files">files.</param>
        /// <param name="htmlUrl">htmlUrl.</param>
        /// <param name="parents">parents.</param>
        /// <param name="sha">sha.</param>
        /// <param name="stats">stats.</param>
        /// <param name="url">url.</param>
        public Commit(User author = default(User), RepoCommit varCommit = default(RepoCommit), User committer = default(User), DateTime created = default(DateTime), List<CommitAffectedFiles> files = default(List<CommitAffectedFiles>), string htmlUrl = default(string), List<CommitMeta> parents = default(List<CommitMeta>), string sha = default(string), CommitStats stats = default(CommitStats), string url = default(string))
        {
            this.Author = author;
            this.VarCommit = varCommit;
            this.Committer = committer;
            this.Created = created;
            this.Files = files;
            this.HtmlUrl = htmlUrl;
            this.Parents = parents;
            this.Sha = sha;
            this.Stats = stats;
            this.Url = url;
        }

        /// <summary>
        /// Gets or Sets Author
        /// </summary>
        [DataMember(Name = "author", EmitDefaultValue = false)]
        public User Author { get; set; }

        /// <summary>
        /// Gets or Sets VarCommit
        /// </summary>
        [DataMember(Name = "commit", EmitDefaultValue = false)]
        public RepoCommit VarCommit { get; set; }

        /// <summary>
        /// Gets or Sets Committer
        /// </summary>
        [DataMember(Name = "committer", EmitDefaultValue = false)]
        public User Committer { get; set; }

        /// <summary>
        /// Gets or Sets Created
        /// </summary>
        [DataMember(Name = "created", EmitDefaultValue = false)]
        public DateTime Created { get; set; }

        /// <summary>
        /// Gets or Sets Files
        /// </summary>
        [DataMember(Name = "files", EmitDefaultValue = false)]
        public List<CommitAffectedFiles> Files { get; set; }

        /// <summary>
        /// Gets or Sets HtmlUrl
        /// </summary>
        [DataMember(Name = "html_url", EmitDefaultValue = false)]
        public string HtmlUrl { get; set; }

        /// <summary>
        /// Gets or Sets Parents
        /// </summary>
        [DataMember(Name = "parents", EmitDefaultValue = false)]
        public List<CommitMeta> Parents { get; set; }

        /// <summary>
        /// Gets or Sets Sha
        /// </summary>
        [DataMember(Name = "sha", EmitDefaultValue = false)]
        public string Sha { get; set; }

        /// <summary>
        /// Gets or Sets Stats
        /// </summary>
        [DataMember(Name = "stats", EmitDefaultValue = false)]
        public CommitStats Stats { get; set; }

        /// <summary>
        /// Gets or Sets Url
        /// </summary>
        [DataMember(Name = "url", EmitDefaultValue = false)]
        public string Url { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            StringBuilder sb = new StringBuilder();
            sb.Append("class Commit {\n");
            sb.Append("  Author: ").Append(Author).Append("\n");
            sb.Append("  VarCommit: ").Append(VarCommit).Append("\n");
            sb.Append("  Committer: ").Append(Committer).Append("\n");
            sb.Append("  Created: ").Append(Created).Append("\n");
            sb.Append("  Files: ").Append(Files).Append("\n");
            sb.Append("  HtmlUrl: ").Append(HtmlUrl).Append("\n");
            sb.Append("  Parents: ").Append(Parents).Append("\n");
            sb.Append("  Sha: ").Append(Sha).Append("\n");
            sb.Append("  Stats: ").Append(Stats).Append("\n");
            sb.Append("  Url: ").Append(Url).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public virtual string ToJson()
        {
            return Newtonsoft.Json.JsonConvert.SerializeObject(this, Newtonsoft.Json.Formatting.Indented);
        }

        /// <summary>
        /// To validate all properties of the instance
        /// </summary>
        /// <param name="validationContext">Validation context</param>
        /// <returns>Validation Result</returns>
        IEnumerable<System.ComponentModel.DataAnnotations.ValidationResult> IValidatableObject.Validate(ValidationContext validationContext)
        {
            yield break;
        }
    }

}
