/*
 * Gitea API
 *
 * This documentation describes the Gitea API.
 *
 * The version of the OpenAPI document: 1.22.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Gitea.Net.Model;
using Gitea.Net.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Gitea.Net.Test.Model
{
    /// <summary>
    ///  Class for testing AccessToken
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class AccessTokenTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for AccessToken
        //private AccessToken instance;

        public AccessTokenTests()
        {
            // TODO uncomment below to create an instance of AccessToken
            //instance = new AccessToken();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of AccessToken
        /// </summary>
        [Fact]
        public void AccessTokenInstanceTest()
        {
            // TODO uncomment below to test "IsType" AccessToken
            //Assert.IsType<AccessToken>(instance);
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Scopes'
        /// </summary>
        [Fact]
        public void ScopesTest()
        {
            // TODO unit test for the property 'Scopes'
        }

        /// <summary>
        /// Test the property 'Sha1'
        /// </summary>
        [Fact]
        public void Sha1Test()
        {
            // TODO unit test for the property 'Sha1'
        }

        /// <summary>
        /// Test the property 'TokenLastEight'
        /// </summary>
        [Fact]
        public void TokenLastEightTest()
        {
            // TODO unit test for the property 'TokenLastEight'
        }
    }
}
