/*
 * Gitea API
 *
 * This documentation describes the Gitea API.
 *
 * The version of the OpenAPI document: 1.22.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Gitea.Net.Model;
using Gitea.Net.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Gitea.Net.Test.Model
{
    /// <summary>
    ///  Class for testing Commit
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CommitTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Commit
        //private Commit instance;

        public CommitTests()
        {
            // TODO uncomment below to create an instance of Commit
            //instance = new Commit();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Commit
        /// </summary>
        [Fact]
        public void CommitInstanceTest()
        {
            // TODO uncomment below to test "IsType" Commit
            //Assert.IsType<Commit>(instance);
        }

        /// <summary>
        /// Test the property 'Author'
        /// </summary>
        [Fact]
        public void AuthorTest()
        {
            // TODO unit test for the property 'Author'
        }

        /// <summary>
        /// Test the property 'VarCommit'
        /// </summary>
        [Fact]
        public void VarCommitTest()
        {
            // TODO unit test for the property 'VarCommit'
        }

        /// <summary>
        /// Test the property 'Committer'
        /// </summary>
        [Fact]
        public void CommitterTest()
        {
            // TODO unit test for the property 'Committer'
        }

        /// <summary>
        /// Test the property 'Created'
        /// </summary>
        [Fact]
        public void CreatedTest()
        {
            // TODO unit test for the property 'Created'
        }

        /// <summary>
        /// Test the property 'Files'
        /// </summary>
        [Fact]
        public void FilesTest()
        {
            // TODO unit test for the property 'Files'
        }

        /// <summary>
        /// Test the property 'HtmlUrl'
        /// </summary>
        [Fact]
        public void HtmlUrlTest()
        {
            // TODO unit test for the property 'HtmlUrl'
        }

        /// <summary>
        /// Test the property 'Parents'
        /// </summary>
        [Fact]
        public void ParentsTest()
        {
            // TODO unit test for the property 'Parents'
        }

        /// <summary>
        /// Test the property 'Sha'
        /// </summary>
        [Fact]
        public void ShaTest()
        {
            // TODO unit test for the property 'Sha'
        }

        /// <summary>
        /// Test the property 'Stats'
        /// </summary>
        [Fact]
        public void StatsTest()
        {
            // TODO unit test for the property 'Stats'
        }

        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Fact]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }
    }
}
