/*
 * Gitea API
 *
 * This documentation describes the Gitea API.
 *
 * The version of the OpenAPI document: 1.22.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Gitea.Net.Model;
using Gitea.Net.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Gitea.Net.Test.Model
{
    /// <summary>
    ///  Class for testing CreateMilestoneOption
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreateMilestoneOptionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CreateMilestoneOption
        //private CreateMilestoneOption instance;

        public CreateMilestoneOptionTests()
        {
            // TODO uncomment below to create an instance of CreateMilestoneOption
            //instance = new CreateMilestoneOption();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreateMilestoneOption
        /// </summary>
        [Fact]
        public void CreateMilestoneOptionInstanceTest()
        {
            // TODO uncomment below to test "IsType" CreateMilestoneOption
            //Assert.IsType<CreateMilestoneOption>(instance);
        }

        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }

        /// <summary>
        /// Test the property 'DueOn'
        /// </summary>
        [Fact]
        public void DueOnTest()
        {
            // TODO unit test for the property 'DueOn'
        }

        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Fact]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }

        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Fact]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }
    }
}
