/*
 * Gitea API
 *
 * This documentation describes the Gitea API.
 *
 * The version of the OpenAPI document: 1.22.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Gitea.Net.Model;
using Gitea.Net.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Gitea.Net.Test.Model
{
    /// <summary>
    ///  Class for testing CreateHookOption
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreateHookOptionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CreateHookOption
        //private CreateHookOption instance;

        public CreateHookOptionTests()
        {
            // TODO uncomment below to create an instance of CreateHookOption
            //instance = new CreateHookOption();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreateHookOption
        /// </summary>
        [Fact]
        public void CreateHookOptionInstanceTest()
        {
            // TODO uncomment below to test "IsType" CreateHookOption
            //Assert.IsType<CreateHookOption>(instance);
        }

        /// <summary>
        /// Test the property 'Active'
        /// </summary>
        [Fact]
        public void ActiveTest()
        {
            // TODO unit test for the property 'Active'
        }

        /// <summary>
        /// Test the property 'AuthorizationHeader'
        /// </summary>
        [Fact]
        public void AuthorizationHeaderTest()
        {
            // TODO unit test for the property 'AuthorizationHeader'
        }

        /// <summary>
        /// Test the property 'BranchFilter'
        /// </summary>
        [Fact]
        public void BranchFilterTest()
        {
            // TODO unit test for the property 'BranchFilter'
        }

        /// <summary>
        /// Test the property 'Config'
        /// </summary>
        [Fact]
        public void ConfigTest()
        {
            // TODO unit test for the property 'Config'
        }

        /// <summary>
        /// Test the property 'Events'
        /// </summary>
        [Fact]
        public void EventsTest()
        {
            // TODO unit test for the property 'Events'
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }
    }
}
