/*
 * Gitea API
 *
 * This documentation describes the Gitea API.
 *
 * The version of the OpenAPI document: 1.22.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Gitea.Net.Model;
using Gitea.Net.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Gitea.Net.Test.Model
{
    /// <summary>
    ///  Class for testing EditReleaseOption
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EditReleaseOptionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EditReleaseOption
        //private EditReleaseOption instance;

        public EditReleaseOptionTests()
        {
            // TODO uncomment below to create an instance of EditReleaseOption
            //instance = new EditReleaseOption();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EditReleaseOption
        /// </summary>
        [Fact]
        public void EditReleaseOptionInstanceTest()
        {
            // TODO uncomment below to test "IsType" EditReleaseOption
            //Assert.IsType<EditReleaseOption>(instance);
        }

        /// <summary>
        /// Test the property 'Body'
        /// </summary>
        [Fact]
        public void BodyTest()
        {
            // TODO unit test for the property 'Body'
        }

        /// <summary>
        /// Test the property 'Draft'
        /// </summary>
        [Fact]
        public void DraftTest()
        {
            // TODO unit test for the property 'Draft'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Prerelease'
        /// </summary>
        [Fact]
        public void PrereleaseTest()
        {
            // TODO unit test for the property 'Prerelease'
        }

        /// <summary>
        /// Test the property 'TagName'
        /// </summary>
        [Fact]
        public void TagNameTest()
        {
            // TODO unit test for the property 'TagName'
        }

        /// <summary>
        /// Test the property 'TargetCommitish'
        /// </summary>
        [Fact]
        public void TargetCommitishTest()
        {
            // TODO unit test for the property 'TargetCommitish'
        }
    }
}
