/*
 * Gitea API
 *
 * This documentation describes the Gitea API.
 *
 * The version of the OpenAPI document: 1.22.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Gitea.Net.Model;
using Gitea.Net.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Gitea.Net.Test.Model
{
    /// <summary>
    ///  Class for testing GitignoreTemplateInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GitignoreTemplateInfoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GitignoreTemplateInfo
        //private GitignoreTemplateInfo instance;

        public GitignoreTemplateInfoTests()
        {
            // TODO uncomment below to create an instance of GitignoreTemplateInfo
            //instance = new GitignoreTemplateInfo();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GitignoreTemplateInfo
        /// </summary>
        [Fact]
        public void GitignoreTemplateInfoInstanceTest()
        {
            // TODO uncomment below to test "IsType" GitignoreTemplateInfo
            //Assert.IsType<GitignoreTemplateInfo>(instance);
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Source'
        /// </summary>
        [Fact]
        public void SourceTest()
        {
            // TODO unit test for the property 'Source'
        }
    }
}
