/*
 * Gitea API
 *
 * This documentation describes the Gitea API.
 *
 * The version of the OpenAPI document: 1.22.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Gitea.Net.Model;
using Gitea.Net.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Gitea.Net.Test.Model
{
    /// <summary>
    ///  Class for testing IssueMeta
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class IssueMetaTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for IssueMeta
        //private IssueMeta instance;

        public IssueMetaTests()
        {
            // TODO uncomment below to create an instance of IssueMeta
            //instance = new IssueMeta();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of IssueMeta
        /// </summary>
        [Fact]
        public void IssueMetaInstanceTest()
        {
            // TODO uncomment below to test "IsType" IssueMeta
            //Assert.IsType<IssueMeta>(instance);
        }

        /// <summary>
        /// Test the property 'Index'
        /// </summary>
        [Fact]
        public void IndexTest()
        {
            // TODO unit test for the property 'Index'
        }

        /// <summary>
        /// Test the property 'Owner'
        /// </summary>
        [Fact]
        public void OwnerTest()
        {
            // TODO unit test for the property 'Owner'
        }

        /// <summary>
        /// Test the property 'Repo'
        /// </summary>
        [Fact]
        public void RepoTest()
        {
            // TODO unit test for the property 'Repo'
        }
    }
}
