/*
 * Gitea API
 *
 * This documentation describes the Gitea API.
 *
 * The version of the OpenAPI document: 1.22.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Gitea.Net.Model;
using Gitea.Net.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Gitea.Net.Test.Model
{
    /// <summary>
    ///  Class for testing IssueConfigContactLink
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class IssueConfigContactLinkTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for IssueConfigContactLink
        //private IssueConfigContactLink instance;

        public IssueConfigContactLinkTests()
        {
            // TODO uncomment below to create an instance of IssueConfigContactLink
            //instance = new IssueConfigContactLink();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of IssueConfigContactLink
        /// </summary>
        [Fact]
        public void IssueConfigContactLinkInstanceTest()
        {
            // TODO uncomment below to test "IsType" IssueConfigContactLink
            //Assert.IsType<IssueConfigContactLink>(instance);
        }

        /// <summary>
        /// Test the property 'About'
        /// </summary>
        [Fact]
        public void AboutTest()
        {
            // TODO unit test for the property 'About'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Fact]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }
    }
}
