/*
 * Gitea API
 *
 * This documentation describes the Gitea API.
 *
 * The version of the OpenAPI document: 1.22.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Gitea.Net.Model;
using Gitea.Net.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Gitea.Net.Test.Model
{
    /// <summary>
    ///  Class for testing Milestone
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class MilestoneTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Milestone
        //private Milestone instance;

        public MilestoneTests()
        {
            // TODO uncomment below to create an instance of Milestone
            //instance = new Milestone();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Milestone
        /// </summary>
        [Fact]
        public void MilestoneInstanceTest()
        {
            // TODO uncomment below to test "IsType" Milestone
            //Assert.IsType<Milestone>(instance);
        }

        /// <summary>
        /// Test the property 'ClosedAt'
        /// </summary>
        [Fact]
        public void ClosedAtTest()
        {
            // TODO unit test for the property 'ClosedAt'
        }

        /// <summary>
        /// Test the property 'ClosedIssues'
        /// </summary>
        [Fact]
        public void ClosedIssuesTest()
        {
            // TODO unit test for the property 'ClosedIssues'
        }

        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }

        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }

        /// <summary>
        /// Test the property 'DueOn'
        /// </summary>
        [Fact]
        public void DueOnTest()
        {
            // TODO unit test for the property 'DueOn'
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'OpenIssues'
        /// </summary>
        [Fact]
        public void OpenIssuesTest()
        {
            // TODO unit test for the property 'OpenIssues'
        }

        /// <summary>
        /// Test the property 'State'
        /// </summary>
        [Fact]
        public void StateTest()
        {
            // TODO unit test for the property 'State'
        }

        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Fact]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }

        /// <summary>
        /// Test the property 'UpdatedAt'
        /// </summary>
        [Fact]
        public void UpdatedAtTest()
        {
            // TODO unit test for the property 'UpdatedAt'
        }
    }
}
