/*
 * Gitea API
 *
 * This documentation describes the Gitea API.
 *
 * The version of the OpenAPI document: 1.22.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Gitea.Net.Model;
using Gitea.Net.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Gitea.Net.Test.Model
{
    /// <summary>
    ///  Class for testing PayloadCommit
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PayloadCommitTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PayloadCommit
        //private PayloadCommit instance;

        public PayloadCommitTests()
        {
            // TODO uncomment below to create an instance of PayloadCommit
            //instance = new PayloadCommit();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PayloadCommit
        /// </summary>
        [Fact]
        public void PayloadCommitInstanceTest()
        {
            // TODO uncomment below to test "IsType" PayloadCommit
            //Assert.IsType<PayloadCommit>(instance);
        }

        /// <summary>
        /// Test the property 'Added'
        /// </summary>
        [Fact]
        public void AddedTest()
        {
            // TODO unit test for the property 'Added'
        }

        /// <summary>
        /// Test the property 'Author'
        /// </summary>
        [Fact]
        public void AuthorTest()
        {
            // TODO unit test for the property 'Author'
        }

        /// <summary>
        /// Test the property 'Committer'
        /// </summary>
        [Fact]
        public void CommitterTest()
        {
            // TODO unit test for the property 'Committer'
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }

        /// <summary>
        /// Test the property 'Modified'
        /// </summary>
        [Fact]
        public void ModifiedTest()
        {
            // TODO unit test for the property 'Modified'
        }

        /// <summary>
        /// Test the property 'Removed'
        /// </summary>
        [Fact]
        public void RemovedTest()
        {
            // TODO unit test for the property 'Removed'
        }

        /// <summary>
        /// Test the property 'Timestamp'
        /// </summary>
        [Fact]
        public void TimestampTest()
        {
            // TODO unit test for the property 'Timestamp'
        }

        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Fact]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }

        /// <summary>
        /// Test the property 'Verification'
        /// </summary>
        [Fact]
        public void VerificationTest()
        {
            // TODO unit test for the property 'Verification'
        }
    }
}
