/*
 * Gitea API
 *
 * This documentation describes the Gitea API.
 *
 * The version of the OpenAPI document: 1.22.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Gitea.Net.Model;
using Gitea.Net.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Gitea.Net.Test.Model
{
    /// <summary>
    ///  Class for testing PayloadCommitVerification
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PayloadCommitVerificationTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PayloadCommitVerification
        //private PayloadCommitVerification instance;

        public PayloadCommitVerificationTests()
        {
            // TODO uncomment below to create an instance of PayloadCommitVerification
            //instance = new PayloadCommitVerification();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PayloadCommitVerification
        /// </summary>
        [Fact]
        public void PayloadCommitVerificationInstanceTest()
        {
            // TODO uncomment below to test "IsType" PayloadCommitVerification
            //Assert.IsType<PayloadCommitVerification>(instance);
        }

        /// <summary>
        /// Test the property 'Payload'
        /// </summary>
        [Fact]
        public void PayloadTest()
        {
            // TODO unit test for the property 'Payload'
        }

        /// <summary>
        /// Test the property 'Reason'
        /// </summary>
        [Fact]
        public void ReasonTest()
        {
            // TODO unit test for the property 'Reason'
        }

        /// <summary>
        /// Test the property 'Signature'
        /// </summary>
        [Fact]
        public void SignatureTest()
        {
            // TODO unit test for the property 'Signature'
        }

        /// <summary>
        /// Test the property 'Signer'
        /// </summary>
        [Fact]
        public void SignerTest()
        {
            // TODO unit test for the property 'Signer'
        }

        /// <summary>
        /// Test the property 'Verified'
        /// </summary>
        [Fact]
        public void VerifiedTest()
        {
            // TODO unit test for the property 'Verified'
        }
    }
}
