/*
 * Gitea API
 *
 * This documentation describes the Gitea API.
 *
 * The version of the OpenAPI document: 1.22.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Gitea.Net.Model;
using Gitea.Net.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Gitea.Net.Test.Model
{
    /// <summary>
    ///  Class for testing RepoCreateReleaseAttachmentRequest
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RepoCreateReleaseAttachmentRequestTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RepoCreateReleaseAttachmentRequest
        //private RepoCreateReleaseAttachmentRequest instance;

        public RepoCreateReleaseAttachmentRequestTests()
        {
            // TODO uncomment below to create an instance of RepoCreateReleaseAttachmentRequest
            //instance = new RepoCreateReleaseAttachmentRequest();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RepoCreateReleaseAttachmentRequest
        /// </summary>
        [Fact]
        public void RepoCreateReleaseAttachmentRequestInstanceTest()
        {
            // TODO uncomment below to test "IsType" RepoCreateReleaseAttachmentRequest
            //Assert.IsType<RepoCreateReleaseAttachmentRequest>(instance);
        }

        /// <summary>
        /// Test the property 'Attachment'
        /// </summary>
        [Fact]
        public void AttachmentTest()
        {
            // TODO unit test for the property 'Attachment'
        }
    }
}
