/*
 * Gitea API
 *
 * This documentation describes the Gitea API.
 *
 * The version of the OpenAPI document: 1.22.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Gitea.Net.Model;
using Gitea.Net.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Gitea.Net.Test.Model
{
    /// <summary>
    ///  Class for testing RepoCommit
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class RepoCommitTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for RepoCommit
        //private RepoCommit instance;

        public RepoCommitTests()
        {
            // TODO uncomment below to create an instance of RepoCommit
            //instance = new RepoCommit();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of RepoCommit
        /// </summary>
        [Fact]
        public void RepoCommitInstanceTest()
        {
            // TODO uncomment below to test "IsType" RepoCommit
            //Assert.IsType<RepoCommit>(instance);
        }

        /// <summary>
        /// Test the property 'Author'
        /// </summary>
        [Fact]
        public void AuthorTest()
        {
            // TODO unit test for the property 'Author'
        }

        /// <summary>
        /// Test the property 'Committer'
        /// </summary>
        [Fact]
        public void CommitterTest()
        {
            // TODO unit test for the property 'Committer'
        }

        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }

        /// <summary>
        /// Test the property 'Tree'
        /// </summary>
        [Fact]
        public void TreeTest()
        {
            // TODO unit test for the property 'Tree'
        }

        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Fact]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }

        /// <summary>
        /// Test the property 'Verification'
        /// </summary>
        [Fact]
        public void VerificationTest()
        {
            // TODO unit test for the property 'Verification'
        }
    }
}
