/*
 * Gitea API
 *
 * This documentation describes the Gitea API.
 *
 * The version of the OpenAPI document: 1.22.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Gitea.Net.Model;
using Gitea.Net.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Gitea.Net.Test.Model
{
    /// <summary>
    ///  Class for testing Tag
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TagTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Tag
        //private Tag instance;

        public TagTests()
        {
            // TODO uncomment below to create an instance of Tag
            //instance = new Tag();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Tag
        /// </summary>
        [Fact]
        public void TagInstanceTest()
        {
            // TODO uncomment below to test "IsType" Tag
            //Assert.IsType<Tag>(instance);
        }

        /// <summary>
        /// Test the property 'Commit'
        /// </summary>
        [Fact]
        public void CommitTest()
        {
            // TODO unit test for the property 'Commit'
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'TarballUrl'
        /// </summary>
        [Fact]
        public void TarballUrlTest()
        {
            // TODO unit test for the property 'TarballUrl'
        }

        /// <summary>
        /// Test the property 'ZipballUrl'
        /// </summary>
        [Fact]
        public void ZipballUrlTest()
        {
            // TODO unit test for the property 'ZipballUrl'
        }
    }
}
