/*
 * Gitea API
 *
 * This documentation describes the Gitea API.
 *
 * The version of the OpenAPI document: 1.22.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Gitea.Net.Model;
using Gitea.Net.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Gitea.Net.Test.Model
{
    /// <summary>
    ///  Class for testing TransferRepoOption
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TransferRepoOptionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TransferRepoOption
        //private TransferRepoOption instance;

        public TransferRepoOptionTests()
        {
            // TODO uncomment below to create an instance of TransferRepoOption
            //instance = new TransferRepoOption();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TransferRepoOption
        /// </summary>
        [Fact]
        public void TransferRepoOptionInstanceTest()
        {
            // TODO uncomment below to test "IsType" TransferRepoOption
            //Assert.IsType<TransferRepoOption>(instance);
        }

        /// <summary>
        /// Test the property 'NewOwner'
        /// </summary>
        [Fact]
        public void NewOwnerTest()
        {
            // TODO unit test for the property 'NewOwner'
        }

        /// <summary>
        /// Test the property 'TeamIds'
        /// </summary>
        [Fact]
        public void TeamIdsTest()
        {
            // TODO unit test for the property 'TeamIds'
        }
    }
}
