/*
 * Gitea API
 *
 * This documentation describes the Gitea API.
 *
 * The version of the OpenAPI document: 1.22.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Gitea.Net.Model;
using Gitea.Net.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Gitea.Net.Test.Model
{
    /// <summary>
    ///  Class for testing User
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UserTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for User
        //private User instance;

        public UserTests()
        {
            // TODO uncomment below to create an instance of User
            //instance = new User();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of User
        /// </summary>
        [Fact]
        public void UserInstanceTest()
        {
            // TODO uncomment below to test "IsType" User
            //Assert.IsType<User>(instance);
        }

        /// <summary>
        /// Test the property 'Active'
        /// </summary>
        [Fact]
        public void ActiveTest()
        {
            // TODO unit test for the property 'Active'
        }

        /// <summary>
        /// Test the property 'AvatarUrl'
        /// </summary>
        [Fact]
        public void AvatarUrlTest()
        {
            // TODO unit test for the property 'AvatarUrl'
        }

        /// <summary>
        /// Test the property 'Created'
        /// </summary>
        [Fact]
        public void CreatedTest()
        {
            // TODO unit test for the property 'Created'
        }

        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }

        /// <summary>
        /// Test the property 'Email'
        /// </summary>
        [Fact]
        public void EmailTest()
        {
            // TODO unit test for the property 'Email'
        }

        /// <summary>
        /// Test the property 'FollowersCount'
        /// </summary>
        [Fact]
        public void FollowersCountTest()
        {
            // TODO unit test for the property 'FollowersCount'
        }

        /// <summary>
        /// Test the property 'FollowingCount'
        /// </summary>
        [Fact]
        public void FollowingCountTest()
        {
            // TODO unit test for the property 'FollowingCount'
        }

        /// <summary>
        /// Test the property 'FullName'
        /// </summary>
        [Fact]
        public void FullNameTest()
        {
            // TODO unit test for the property 'FullName'
        }

        /// <summary>
        /// Test the property 'HtmlUrl'
        /// </summary>
        [Fact]
        public void HtmlUrlTest()
        {
            // TODO unit test for the property 'HtmlUrl'
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'IsAdmin'
        /// </summary>
        [Fact]
        public void IsAdminTest()
        {
            // TODO unit test for the property 'IsAdmin'
        }

        /// <summary>
        /// Test the property 'Language'
        /// </summary>
        [Fact]
        public void LanguageTest()
        {
            // TODO unit test for the property 'Language'
        }

        /// <summary>
        /// Test the property 'LastLogin'
        /// </summary>
        [Fact]
        public void LastLoginTest()
        {
            // TODO unit test for the property 'LastLogin'
        }

        /// <summary>
        /// Test the property 'Location'
        /// </summary>
        [Fact]
        public void LocationTest()
        {
            // TODO unit test for the property 'Location'
        }

        /// <summary>
        /// Test the property 'Login'
        /// </summary>
        [Fact]
        public void LoginTest()
        {
            // TODO unit test for the property 'Login'
        }

        /// <summary>
        /// Test the property 'LoginName'
        /// </summary>
        [Fact]
        public void LoginNameTest()
        {
            // TODO unit test for the property 'LoginName'
        }

        /// <summary>
        /// Test the property 'ProhibitLogin'
        /// </summary>
        [Fact]
        public void ProhibitLoginTest()
        {
            // TODO unit test for the property 'ProhibitLogin'
        }

        /// <summary>
        /// Test the property 'Restricted'
        /// </summary>
        [Fact]
        public void RestrictedTest()
        {
            // TODO unit test for the property 'Restricted'
        }

        /// <summary>
        /// Test the property 'SourceId'
        /// </summary>
        [Fact]
        public void SourceIdTest()
        {
            // TODO unit test for the property 'SourceId'
        }

        /// <summary>
        /// Test the property 'StarredReposCount'
        /// </summary>
        [Fact]
        public void StarredReposCountTest()
        {
            // TODO unit test for the property 'StarredReposCount'
        }

        /// <summary>
        /// Test the property 'Visibility'
        /// </summary>
        [Fact]
        public void VisibilityTest()
        {
            // TODO unit test for the property 'Visibility'
        }

        /// <summary>
        /// Test the property 'Website'
        /// </summary>
        [Fact]
        public void WebsiteTest()
        {
            // TODO unit test for the property 'Website'
        }
    }
}
