/*
 * Gitea API
 *
 * This documentation describes the Gitea API.
 *
 * The version of the OpenAPI document: 1.22.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Gitea.Net.Model;
using Gitea.Net.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Gitea.Net.Test.Model
{
    /// <summary>
    ///  Class for testing WikiPage
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WikiPageTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for WikiPage
        //private WikiPage instance;

        public WikiPageTests()
        {
            // TODO uncomment below to create an instance of WikiPage
            //instance = new WikiPage();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WikiPage
        /// </summary>
        [Fact]
        public void WikiPageInstanceTest()
        {
            // TODO uncomment below to test "IsType" WikiPage
            //Assert.IsType<WikiPage>(instance);
        }

        /// <summary>
        /// Test the property 'CommitCount'
        /// </summary>
        [Fact]
        public void CommitCountTest()
        {
            // TODO unit test for the property 'CommitCount'
        }

        /// <summary>
        /// Test the property 'ContentBase64'
        /// </summary>
        [Fact]
        public void ContentBase64Test()
        {
            // TODO unit test for the property 'ContentBase64'
        }

        /// <summary>
        /// Test the property 'Footer'
        /// </summary>
        [Fact]
        public void FooterTest()
        {
            // TODO unit test for the property 'Footer'
        }

        /// <summary>
        /// Test the property 'HtmlUrl'
        /// </summary>
        [Fact]
        public void HtmlUrlTest()
        {
            // TODO unit test for the property 'HtmlUrl'
        }

        /// <summary>
        /// Test the property 'LastCommit'
        /// </summary>
        [Fact]
        public void LastCommitTest()
        {
            // TODO unit test for the property 'LastCommit'
        }

        /// <summary>
        /// Test the property 'Sidebar'
        /// </summary>
        [Fact]
        public void SidebarTest()
        {
            // TODO unit test for the property 'Sidebar'
        }

        /// <summary>
        /// Test the property 'SubUrl'
        /// </summary>
        [Fact]
        public void SubUrlTest()
        {
            // TODO unit test for the property 'SubUrl'
        }

        /// <summary>
        /// Test the property 'Title'
        /// </summary>
        [Fact]
        public void TitleTest()
        {
            // TODO unit test for the property 'Title'
        }
    }
}
