/*
 * Gitea API
 *
 * This documentation describes the Gitea API.
 *
 * The version of the OpenAPI document: 1.22.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing ContentsResponse
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ContentsResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ContentsResponse
        //private ContentsResponse instance;

        public ContentsResponseTests()
        {
            // TODO uncomment below to create an instance of ContentsResponse
            //instance = new ContentsResponse();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ContentsResponse
        /// </summary>
        [Fact]
        public void ContentsResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" ContentsResponse
            //Assert.IsType<ContentsResponse>(instance);
        }

        /// <summary>
        /// Test the property 'Links'
        /// </summary>
        [Fact]
        public void LinksTest()
        {
            // TODO unit test for the property 'Links'
        }

        /// <summary>
        /// Test the property 'Content'
        /// </summary>
        [Fact]
        public void ContentTest()
        {
            // TODO unit test for the property 'Content'
        }

        /// <summary>
        /// Test the property 'DownloadUrl'
        /// </summary>
        [Fact]
        public void DownloadUrlTest()
        {
            // TODO unit test for the property 'DownloadUrl'
        }

        /// <summary>
        /// Test the property 'Encoding'
        /// </summary>
        [Fact]
        public void EncodingTest()
        {
            // TODO unit test for the property 'Encoding'
        }

        /// <summary>
        /// Test the property 'GitUrl'
        /// </summary>
        [Fact]
        public void GitUrlTest()
        {
            // TODO unit test for the property 'GitUrl'
        }

        /// <summary>
        /// Test the property 'HtmlUrl'
        /// </summary>
        [Fact]
        public void HtmlUrlTest()
        {
            // TODO unit test for the property 'HtmlUrl'
        }

        /// <summary>
        /// Test the property 'LastCommitSha'
        /// </summary>
        [Fact]
        public void LastCommitShaTest()
        {
            // TODO unit test for the property 'LastCommitSha'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Path'
        /// </summary>
        [Fact]
        public void PathTest()
        {
            // TODO unit test for the property 'Path'
        }

        /// <summary>
        /// Test the property 'Sha'
        /// </summary>
        [Fact]
        public void ShaTest()
        {
            // TODO unit test for the property 'Sha'
        }

        /// <summary>
        /// Test the property 'Size'
        /// </summary>
        [Fact]
        public void SizeTest()
        {
            // TODO unit test for the property 'Size'
        }

        /// <summary>
        /// Test the property 'SubmoduleGitUrl'
        /// </summary>
        [Fact]
        public void SubmoduleGitUrlTest()
        {
            // TODO unit test for the property 'SubmoduleGitUrl'
        }

        /// <summary>
        /// Test the property 'Target'
        /// </summary>
        [Fact]
        public void TargetTest()
        {
            // TODO unit test for the property 'Target'
        }

        /// <summary>
        /// Test the property 'Type'
        /// </summary>
        [Fact]
        public void TypeTest()
        {
            // TODO unit test for the property 'Type'
        }

        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Fact]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }
    }
}
