/*
 * Gitea API
 *
 * This documentation describes the Gitea API.
 *
 * The version of the OpenAPI document: 1.22.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing CreateOAuth2ApplicationOptions
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreateOAuth2ApplicationOptionsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CreateOAuth2ApplicationOptions
        //private CreateOAuth2ApplicationOptions instance;

        public CreateOAuth2ApplicationOptionsTests()
        {
            // TODO uncomment below to create an instance of CreateOAuth2ApplicationOptions
            //instance = new CreateOAuth2ApplicationOptions();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreateOAuth2ApplicationOptions
        /// </summary>
        [Fact]
        public void CreateOAuth2ApplicationOptionsInstanceTest()
        {
            // TODO uncomment below to test "IsType" CreateOAuth2ApplicationOptions
            //Assert.IsType<CreateOAuth2ApplicationOptions>(instance);
        }

        /// <summary>
        /// Test the property 'ConfidentialClient'
        /// </summary>
        [Fact]
        public void ConfidentialClientTest()
        {
            // TODO unit test for the property 'ConfidentialClient'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'RedirectUris'
        /// </summary>
        [Fact]
        public void RedirectUrisTest()
        {
            // TODO unit test for the property 'RedirectUris'
        }
    }
}
