/*
 * Gitea API
 *
 * This documentation describes the Gitea API.
 *
 * The version of the OpenAPI document: 1.22.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing CreateLabelOption
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreateLabelOptionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CreateLabelOption
        //private CreateLabelOption instance;

        public CreateLabelOptionTests()
        {
            // TODO uncomment below to create an instance of CreateLabelOption
            //instance = new CreateLabelOption();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreateLabelOption
        /// </summary>
        [Fact]
        public void CreateLabelOptionInstanceTest()
        {
            // TODO uncomment below to test "IsType" CreateLabelOption
            //Assert.IsType<CreateLabelOption>(instance);
        }

        /// <summary>
        /// Test the property 'Color'
        /// </summary>
        [Fact]
        public void ColorTest()
        {
            // TODO unit test for the property 'Color'
        }

        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }

        /// <summary>
        /// Test the property 'Exclusive'
        /// </summary>
        [Fact]
        public void ExclusiveTest()
        {
            // TODO unit test for the property 'Exclusive'
        }

        /// <summary>
        /// Test the property 'IsArchived'
        /// </summary>
        [Fact]
        public void IsArchivedTest()
        {
            // TODO unit test for the property 'IsArchived'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }
    }
}
