/*
 * Gitea API
 *
 * This documentation describes the Gitea API.
 *
 * The version of the OpenAPI document: 1.22.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing CreateAccessTokenOption
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class CreateAccessTokenOptionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for CreateAccessTokenOption
        //private CreateAccessTokenOption instance;

        public CreateAccessTokenOptionTests()
        {
            // TODO uncomment below to create an instance of CreateAccessTokenOption
            //instance = new CreateAccessTokenOption();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of CreateAccessTokenOption
        /// </summary>
        [Fact]
        public void CreateAccessTokenOptionInstanceTest()
        {
            // TODO uncomment below to test "IsType" CreateAccessTokenOption
            //Assert.IsType<CreateAccessTokenOption>(instance);
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Scopes'
        /// </summary>
        [Fact]
        public void ScopesTest()
        {
            // TODO unit test for the property 'Scopes'
        }
    }
}
