/*
 * Gitea API
 *
 * This documentation describes the Gitea API.
 *
 * The version of the OpenAPI document: 1.22.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing EditTeamOption
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class EditTeamOptionTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for EditTeamOption
        //private EditTeamOption instance;

        public EditTeamOptionTests()
        {
            // TODO uncomment below to create an instance of EditTeamOption
            //instance = new EditTeamOption();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of EditTeamOption
        /// </summary>
        [Fact]
        public void EditTeamOptionInstanceTest()
        {
            // TODO uncomment below to test "IsType" EditTeamOption
            //Assert.IsType<EditTeamOption>(instance);
        }

        /// <summary>
        /// Test the property 'CanCreateOrgRepo'
        /// </summary>
        [Fact]
        public void CanCreateOrgRepoTest()
        {
            // TODO unit test for the property 'CanCreateOrgRepo'
        }

        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }

        /// <summary>
        /// Test the property 'IncludesAllRepositories'
        /// </summary>
        [Fact]
        public void IncludesAllRepositoriesTest()
        {
            // TODO unit test for the property 'IncludesAllRepositories'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Permission'
        /// </summary>
        [Fact]
        public void PermissionTest()
        {
            // TODO unit test for the property 'Permission'
        }

        /// <summary>
        /// Test the property 'Units'
        /// </summary>
        [Fact]
        public void UnitsTest()
        {
            // TODO unit test for the property 'Units'
        }

        /// <summary>
        /// Test the property 'UnitsMap'
        /// </summary>
        [Fact]
        public void UnitsMapTest()
        {
            // TODO unit test for the property 'UnitsMap'
        }
    }
}
