/*
 * Gitea API
 *
 * This documentation describes the Gitea API.
 *
 * The version of the OpenAPI document: 1.22.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing ExternalTracker
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class ExternalTrackerTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for ExternalTracker
        //private ExternalTracker instance;

        public ExternalTrackerTests()
        {
            // TODO uncomment below to create an instance of ExternalTracker
            //instance = new ExternalTracker();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of ExternalTracker
        /// </summary>
        [Fact]
        public void ExternalTrackerInstanceTest()
        {
            // TODO uncomment below to test "IsType" ExternalTracker
            //Assert.IsType<ExternalTracker>(instance);
        }

        /// <summary>
        /// Test the property 'ExternalTrackerFormat'
        /// </summary>
        [Fact]
        public void ExternalTrackerFormatTest()
        {
            // TODO unit test for the property 'ExternalTrackerFormat'
        }

        /// <summary>
        /// Test the property 'ExternalTrackerRegexpPattern'
        /// </summary>
        [Fact]
        public void ExternalTrackerRegexpPatternTest()
        {
            // TODO unit test for the property 'ExternalTrackerRegexpPattern'
        }

        /// <summary>
        /// Test the property 'ExternalTrackerStyle'
        /// </summary>
        [Fact]
        public void ExternalTrackerStyleTest()
        {
            // TODO unit test for the property 'ExternalTrackerStyle'
        }

        /// <summary>
        /// Test the property 'ExternalTrackerUrl'
        /// </summary>
        [Fact]
        public void ExternalTrackerUrlTest()
        {
            // TODO unit test for the property 'ExternalTrackerUrl'
        }
    }
}
