/*
 * Gitea API
 *
 * This documentation describes the Gitea API.
 *
 * The version of the OpenAPI document: 1.22.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing GeneralAPISettings
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GeneralAPISettingsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GeneralAPISettings
        //private GeneralAPISettings instance;

        public GeneralAPISettingsTests()
        {
            // TODO uncomment below to create an instance of GeneralAPISettings
            //instance = new GeneralAPISettings();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GeneralAPISettings
        /// </summary>
        [Fact]
        public void GeneralAPISettingsInstanceTest()
        {
            // TODO uncomment below to test "IsType" GeneralAPISettings
            //Assert.IsType<GeneralAPISettings>(instance);
        }

        /// <summary>
        /// Test the property 'DefaultGitTreesPerPage'
        /// </summary>
        [Fact]
        public void DefaultGitTreesPerPageTest()
        {
            // TODO unit test for the property 'DefaultGitTreesPerPage'
        }

        /// <summary>
        /// Test the property 'DefaultMaxBlobSize'
        /// </summary>
        [Fact]
        public void DefaultMaxBlobSizeTest()
        {
            // TODO unit test for the property 'DefaultMaxBlobSize'
        }

        /// <summary>
        /// Test the property 'DefaultPagingNum'
        /// </summary>
        [Fact]
        public void DefaultPagingNumTest()
        {
            // TODO unit test for the property 'DefaultPagingNum'
        }

        /// <summary>
        /// Test the property 'MaxResponseItems'
        /// </summary>
        [Fact]
        public void MaxResponseItemsTest()
        {
            // TODO unit test for the property 'MaxResponseItems'
        }
    }
}
