/*
 * Gitea API
 *
 * This documentation describes the Gitea API.
 *
 * The version of the OpenAPI document: 1.22.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing GeneralRepoSettings
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class GeneralRepoSettingsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for GeneralRepoSettings
        //private GeneralRepoSettings instance;

        public GeneralRepoSettingsTests()
        {
            // TODO uncomment below to create an instance of GeneralRepoSettings
            //instance = new GeneralRepoSettings();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of GeneralRepoSettings
        /// </summary>
        [Fact]
        public void GeneralRepoSettingsInstanceTest()
        {
            // TODO uncomment below to test "IsType" GeneralRepoSettings
            //Assert.IsType<GeneralRepoSettings>(instance);
        }

        /// <summary>
        /// Test the property 'HttpGitDisabled'
        /// </summary>
        [Fact]
        public void HttpGitDisabledTest()
        {
            // TODO unit test for the property 'HttpGitDisabled'
        }

        /// <summary>
        /// Test the property 'LfsDisabled'
        /// </summary>
        [Fact]
        public void LfsDisabledTest()
        {
            // TODO unit test for the property 'LfsDisabled'
        }

        /// <summary>
        /// Test the property 'MigrationsDisabled'
        /// </summary>
        [Fact]
        public void MigrationsDisabledTest()
        {
            // TODO unit test for the property 'MigrationsDisabled'
        }

        /// <summary>
        /// Test the property 'MirrorsDisabled'
        /// </summary>
        [Fact]
        public void MirrorsDisabledTest()
        {
            // TODO unit test for the property 'MirrorsDisabled'
        }

        /// <summary>
        /// Test the property 'StarsDisabled'
        /// </summary>
        [Fact]
        public void StarsDisabledTest()
        {
            // TODO unit test for the property 'StarsDisabled'
        }

        /// <summary>
        /// Test the property 'TimeTrackingDisabled'
        /// </summary>
        [Fact]
        public void TimeTrackingDisabledTest()
        {
            // TODO unit test for the property 'TimeTrackingDisabled'
        }
    }
}
