/*
 * Gitea API
 *
 * This documentation describes the Gitea API.
 *
 * The version of the OpenAPI document: 1.22.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing LicensesTemplateListEntry
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class LicensesTemplateListEntryTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for LicensesTemplateListEntry
        //private LicensesTemplateListEntry instance;

        public LicensesTemplateListEntryTests()
        {
            // TODO uncomment below to create an instance of LicensesTemplateListEntry
            //instance = new LicensesTemplateListEntry();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of LicensesTemplateListEntry
        /// </summary>
        [Fact]
        public void LicensesTemplateListEntryInstanceTest()
        {
            // TODO uncomment below to test "IsType" LicensesTemplateListEntry
            //Assert.IsType<LicensesTemplateListEntry>(instance);
        }

        /// <summary>
        /// Test the property 'Key'
        /// </summary>
        [Fact]
        public void KeyTest()
        {
            // TODO unit test for the property 'Key'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Fact]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }
    }
}
