/*
 * Gitea API
 *
 * This documentation describes the Gitea API.
 *
 * The version of the OpenAPI document: 1.22.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing NodeInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class NodeInfoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for NodeInfo
        //private NodeInfo instance;

        public NodeInfoTests()
        {
            // TODO uncomment below to create an instance of NodeInfo
            //instance = new NodeInfo();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of NodeInfo
        /// </summary>
        [Fact]
        public void NodeInfoInstanceTest()
        {
            // TODO uncomment below to test "IsType" NodeInfo
            //Assert.IsType<NodeInfo>(instance);
        }

        /// <summary>
        /// Test the property 'Metadata'
        /// </summary>
        [Fact]
        public void MetadataTest()
        {
            // TODO unit test for the property 'Metadata'
        }

        /// <summary>
        /// Test the property 'OpenRegistrations'
        /// </summary>
        [Fact]
        public void OpenRegistrationsTest()
        {
            // TODO unit test for the property 'OpenRegistrations'
        }

        /// <summary>
        /// Test the property 'Protocols'
        /// </summary>
        [Fact]
        public void ProtocolsTest()
        {
            // TODO unit test for the property 'Protocols'
        }

        /// <summary>
        /// Test the property 'Services'
        /// </summary>
        [Fact]
        public void ServicesTest()
        {
            // TODO unit test for the property 'Services'
        }

        /// <summary>
        /// Test the property 'Software'
        /// </summary>
        [Fact]
        public void SoftwareTest()
        {
            // TODO unit test for the property 'Software'
        }

        /// <summary>
        /// Test the property 'Usage'
        /// </summary>
        [Fact]
        public void UsageTest()
        {
            // TODO unit test for the property 'Usage'
        }

        /// <summary>
        /// Test the property 'VarVersion'
        /// </summary>
        [Fact]
        public void VarVersionTest()
        {
            // TODO unit test for the property 'VarVersion'
        }
    }
}
