/*
 * Gitea API
 *
 * This documentation describes the Gitea API.
 *
 * The version of the OpenAPI document: 1.22.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing NodeInfoUsageUsers
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class NodeInfoUsageUsersTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for NodeInfoUsageUsers
        //private NodeInfoUsageUsers instance;

        public NodeInfoUsageUsersTests()
        {
            // TODO uncomment below to create an instance of NodeInfoUsageUsers
            //instance = new NodeInfoUsageUsers();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of NodeInfoUsageUsers
        /// </summary>
        [Fact]
        public void NodeInfoUsageUsersInstanceTest()
        {
            // TODO uncomment below to test "IsType" NodeInfoUsageUsers
            //Assert.IsType<NodeInfoUsageUsers>(instance);
        }

        /// <summary>
        /// Test the property 'ActiveHalfyear'
        /// </summary>
        [Fact]
        public void ActiveHalfyearTest()
        {
            // TODO unit test for the property 'ActiveHalfyear'
        }

        /// <summary>
        /// Test the property 'ActiveMonth'
        /// </summary>
        [Fact]
        public void ActiveMonthTest()
        {
            // TODO unit test for the property 'ActiveMonth'
        }

        /// <summary>
        /// Test the property 'Total'
        /// </summary>
        [Fact]
        public void TotalTest()
        {
            // TODO unit test for the property 'Total'
        }
    }
}
