/*
 * Gitea API
 *
 * This documentation describes the Gitea API.
 *
 * The version of the OpenAPI document: 1.22.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing Note
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class NoteTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for Note
        //private Note instance;

        public NoteTests()
        {
            // TODO uncomment below to create an instance of Note
            //instance = new Note();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of Note
        /// </summary>
        [Fact]
        public void NoteInstanceTest()
        {
            // TODO uncomment below to test "IsType" Note
            //Assert.IsType<Note>(instance);
        }

        /// <summary>
        /// Test the property 'Commit'
        /// </summary>
        [Fact]
        public void CommitTest()
        {
            // TODO unit test for the property 'Commit'
        }

        /// <summary>
        /// Test the property 'Message'
        /// </summary>
        [Fact]
        public void MessageTest()
        {
            // TODO unit test for the property 'Message'
        }
    }
}
