/*
 * Gitea API
 *
 * This documentation describes the Gitea API.
 *
 * The version of the OpenAPI document: 1.22.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing OAuth2Application
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class OAuth2ApplicationTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for OAuth2Application
        //private OAuth2Application instance;

        public OAuth2ApplicationTests()
        {
            // TODO uncomment below to create an instance of OAuth2Application
            //instance = new OAuth2Application();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of OAuth2Application
        /// </summary>
        [Fact]
        public void OAuth2ApplicationInstanceTest()
        {
            // TODO uncomment below to test "IsType" OAuth2Application
            //Assert.IsType<OAuth2Application>(instance);
        }

        /// <summary>
        /// Test the property 'ClientId'
        /// </summary>
        [Fact]
        public void ClientIdTest()
        {
            // TODO unit test for the property 'ClientId'
        }

        /// <summary>
        /// Test the property 'ClientSecret'
        /// </summary>
        [Fact]
        public void ClientSecretTest()
        {
            // TODO unit test for the property 'ClientSecret'
        }

        /// <summary>
        /// Test the property 'ConfidentialClient'
        /// </summary>
        [Fact]
        public void ConfidentialClientTest()
        {
            // TODO unit test for the property 'ConfidentialClient'
        }

        /// <summary>
        /// Test the property 'Created'
        /// </summary>
        [Fact]
        public void CreatedTest()
        {
            // TODO unit test for the property 'Created'
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'RedirectUris'
        /// </summary>
        [Fact]
        public void RedirectUrisTest()
        {
            // TODO unit test for the property 'RedirectUris'
        }
    }
}
