/*
 * Gitea API
 *
 * This documentation describes the Gitea API.
 *
 * The version of the OpenAPI document: 1.22.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing PackageFile
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class PackageFileTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for PackageFile
        //private PackageFile instance;

        public PackageFileTests()
        {
            // TODO uncomment below to create an instance of PackageFile
            //instance = new PackageFile();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of PackageFile
        /// </summary>
        [Fact]
        public void PackageFileInstanceTest()
        {
            // TODO uncomment below to test "IsType" PackageFile
            //Assert.IsType<PackageFile>(instance);
        }

        /// <summary>
        /// Test the property 'Size'
        /// </summary>
        [Fact]
        public void SizeTest()
        {
            // TODO unit test for the property 'Size'
        }

        /// <summary>
        /// Test the property 'Id'
        /// </summary>
        [Fact]
        public void IdTest()
        {
            // TODO unit test for the property 'Id'
        }

        /// <summary>
        /// Test the property 'Md5'
        /// </summary>
        [Fact]
        public void Md5Test()
        {
            // TODO unit test for the property 'Md5'
        }

        /// <summary>
        /// Test the property 'Name'
        /// </summary>
        [Fact]
        public void NameTest()
        {
            // TODO unit test for the property 'Name'
        }

        /// <summary>
        /// Test the property 'Sha1'
        /// </summary>
        [Fact]
        public void Sha1Test()
        {
            // TODO unit test for the property 'Sha1'
        }

        /// <summary>
        /// Test the property 'Sha256'
        /// </summary>
        [Fact]
        public void Sha256Test()
        {
            // TODO unit test for the property 'Sha256'
        }

        /// <summary>
        /// Test the property 'Sha512'
        /// </summary>
        [Fact]
        public void Sha512Test()
        {
            // TODO unit test for the property 'Sha512'
        }
    }
}
