/*
 * Gitea API
 *
 * This documentation describes the Gitea API.
 *
 * The version of the OpenAPI document: 1.22.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing StopWatch
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class StopWatchTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for StopWatch
        //private StopWatch instance;

        public StopWatchTests()
        {
            // TODO uncomment below to create an instance of StopWatch
            //instance = new StopWatch();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of StopWatch
        /// </summary>
        [Fact]
        public void StopWatchInstanceTest()
        {
            // TODO uncomment below to test "IsType" StopWatch
            //Assert.IsType<StopWatch>(instance);
        }

        /// <summary>
        /// Test the property 'Created'
        /// </summary>
        [Fact]
        public void CreatedTest()
        {
            // TODO unit test for the property 'Created'
        }

        /// <summary>
        /// Test the property 'Duration'
        /// </summary>
        [Fact]
        public void DurationTest()
        {
            // TODO unit test for the property 'Duration'
        }

        /// <summary>
        /// Test the property 'IssueIndex'
        /// </summary>
        [Fact]
        public void IssueIndexTest()
        {
            // TODO unit test for the property 'IssueIndex'
        }

        /// <summary>
        /// Test the property 'IssueTitle'
        /// </summary>
        [Fact]
        public void IssueTitleTest()
        {
            // TODO unit test for the property 'IssueTitle'
        }

        /// <summary>
        /// Test the property 'RepoName'
        /// </summary>
        [Fact]
        public void RepoNameTest()
        {
            // TODO unit test for the property 'RepoName'
        }

        /// <summary>
        /// Test the property 'RepoOwnerName'
        /// </summary>
        [Fact]
        public void RepoOwnerNameTest()
        {
            // TODO unit test for the property 'RepoOwnerName'
        }

        /// <summary>
        /// Test the property 'Seconds'
        /// </summary>
        [Fact]
        public void SecondsTest()
        {
            // TODO unit test for the property 'Seconds'
        }
    }
}
