/*
 * Gitea API
 *
 * This documentation describes the Gitea API.
 *
 * The version of the OpenAPI document: 1.22.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing TopicName
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class TopicNameTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for TopicName
        //private TopicName instance;

        public TopicNameTests()
        {
            // TODO uncomment below to create an instance of TopicName
            //instance = new TopicName();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of TopicName
        /// </summary>
        [Fact]
        public void TopicNameInstanceTest()
        {
            // TODO uncomment below to test "IsType" TopicName
            //Assert.IsType<TopicName>(instance);
        }

        /// <summary>
        /// Test the property 'Topics'
        /// </summary>
        [Fact]
        public void TopicsTest()
        {
            // TODO unit test for the property 'Topics'
        }
    }
}
