/*
 * Gitea API
 *
 * This documentation describes the Gitea API.
 *
 * The version of the OpenAPI document: 1.22.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing UserSettingsOptions
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UserSettingsOptionsTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UserSettingsOptions
        //private UserSettingsOptions instance;

        public UserSettingsOptionsTests()
        {
            // TODO uncomment below to create an instance of UserSettingsOptions
            //instance = new UserSettingsOptions();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UserSettingsOptions
        /// </summary>
        [Fact]
        public void UserSettingsOptionsInstanceTest()
        {
            // TODO uncomment below to test "IsType" UserSettingsOptions
            //Assert.IsType<UserSettingsOptions>(instance);
        }

        /// <summary>
        /// Test the property 'Description'
        /// </summary>
        [Fact]
        public void DescriptionTest()
        {
            // TODO unit test for the property 'Description'
        }

        /// <summary>
        /// Test the property 'DiffViewStyle'
        /// </summary>
        [Fact]
        public void DiffViewStyleTest()
        {
            // TODO unit test for the property 'DiffViewStyle'
        }

        /// <summary>
        /// Test the property 'FullName'
        /// </summary>
        [Fact]
        public void FullNameTest()
        {
            // TODO unit test for the property 'FullName'
        }

        /// <summary>
        /// Test the property 'HideActivity'
        /// </summary>
        [Fact]
        public void HideActivityTest()
        {
            // TODO unit test for the property 'HideActivity'
        }

        /// <summary>
        /// Test the property 'HideEmail'
        /// </summary>
        [Fact]
        public void HideEmailTest()
        {
            // TODO unit test for the property 'HideEmail'
        }

        /// <summary>
        /// Test the property 'Language'
        /// </summary>
        [Fact]
        public void LanguageTest()
        {
            // TODO unit test for the property 'Language'
        }

        /// <summary>
        /// Test the property 'Location'
        /// </summary>
        [Fact]
        public void LocationTest()
        {
            // TODO unit test for the property 'Location'
        }

        /// <summary>
        /// Test the property 'Theme'
        /// </summary>
        [Fact]
        public void ThemeTest()
        {
            // TODO unit test for the property 'Theme'
        }

        /// <summary>
        /// Test the property 'Website'
        /// </summary>
        [Fact]
        public void WebsiteTest()
        {
            // TODO unit test for the property 'Website'
        }
    }
}
