/*
 * Gitea API
 *
 * This documentation describes the Gitea API.
 *
 * The version of the OpenAPI document: 1.22.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing UserSearch200Response
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class UserSearch200ResponseTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for UserSearch200Response
        //private UserSearch200Response instance;

        public UserSearch200ResponseTests()
        {
            // TODO uncomment below to create an instance of UserSearch200Response
            //instance = new UserSearch200Response();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of UserSearch200Response
        /// </summary>
        [Fact]
        public void UserSearch200ResponseInstanceTest()
        {
            // TODO uncomment below to test "IsType" UserSearch200Response
            //Assert.IsType<UserSearch200Response>(instance);
        }

        /// <summary>
        /// Test the property 'Data'
        /// </summary>
        [Fact]
        public void DataTest()
        {
            // TODO unit test for the property 'Data'
        }

        /// <summary>
        /// Test the property 'Ok'
        /// </summary>
        [Fact]
        public void OkTest()
        {
            // TODO unit test for the property 'Ok'
        }
    }
}
