/*
 * Gitea API
 *
 * This documentation describes the Gitea API.
 *
 * The version of the OpenAPI document: 1.22.0
 * Generated by: https://github.com/openapitools/openapi-generator.git
 */


using Xunit;

using System;
using System.Linq;
using System.IO;
using System.Collections.Generic;
using Org.OpenAPITools.Model;
using Org.OpenAPITools.Client;
using System.Reflection;
using Newtonsoft.Json;

namespace Org.OpenAPITools.Test.Model
{
    /// <summary>
    ///  Class for testing WatchInfo
    /// </summary>
    /// <remarks>
    /// This file is automatically generated by OpenAPI Generator (https://openapi-generator.tech).
    /// Please update the test case below to test the model.
    /// </remarks>
    public class WatchInfoTests : IDisposable
    {
        // TODO uncomment below to declare an instance variable for WatchInfo
        //private WatchInfo instance;

        public WatchInfoTests()
        {
            // TODO uncomment below to create an instance of WatchInfo
            //instance = new WatchInfo();
        }

        public void Dispose()
        {
            // Cleanup when everything is done.
        }

        /// <summary>
        /// Test an instance of WatchInfo
        /// </summary>
        [Fact]
        public void WatchInfoInstanceTest()
        {
            // TODO uncomment below to test "IsType" WatchInfo
            //Assert.IsType<WatchInfo>(instance);
        }

        /// <summary>
        /// Test the property 'CreatedAt'
        /// </summary>
        [Fact]
        public void CreatedAtTest()
        {
            // TODO unit test for the property 'CreatedAt'
        }

        /// <summary>
        /// Test the property 'Ignored'
        /// </summary>
        [Fact]
        public void IgnoredTest()
        {
            // TODO unit test for the property 'Ignored'
        }

        /// <summary>
        /// Test the property 'Reason'
        /// </summary>
        [Fact]
        public void ReasonTest()
        {
            // TODO unit test for the property 'Reason'
        }

        /// <summary>
        /// Test the property 'RepositoryUrl'
        /// </summary>
        [Fact]
        public void RepositoryUrlTest()
        {
            // TODO unit test for the property 'RepositoryUrl'
        }

        /// <summary>
        /// Test the property 'Subscribed'
        /// </summary>
        [Fact]
        public void SubscribedTest()
        {
            // TODO unit test for the property 'Subscribed'
        }

        /// <summary>
        /// Test the property 'Url'
        /// </summary>
        [Fact]
        public void UrlTest()
        {
            // TODO unit test for the property 'Url'
        }
    }
}
